modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="themakkersmod"
version="1.0.0."
displayName="The Makkers Mod"
credits="Mod created by JoasJSD & ieguana"
displayURL="https://mcreator.net"
authors="JoasJSD, ieguana"

[[dependencies.themakkersmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




